### ISSUE TITLE
Sync up with SJ and Kent on initial discussions with VR cohort.

### ISSUE THREAD

**Issue by Nolski** [FOSSRIT/librecorps#2]
# Overview

In order to accurately determine the amount of hours I will need to charge unicef for my contracting, It'd be helpful for me to get a general overview of what discussions we have had with the VR cohort already. What's outstanding. 

@itprofjacobs, would this be possible?

**Comment by itprofjacobs** [comment]
1. Nothing other than our initial presentations during their on-boarding week.

2.  The Position description they advertised specified a cap of two days a week, a duration of six months (renewable once) and a $ amount cap of $50k if I remember right.  You should double check that posting. I vaguely remember a conversation where they were hoping folks would bill at $450/day or so, but that comes in well under the $50k 

3.  You should be asking them if they expect Gates to also fit under that cap and $ amount or if they’re raising your cap and hours to 1.5  or 2 times the advertised position.  

4. You should also know that I told them RIT’d be coordinating efforts with you, and willing to shuffle who works with who (Kent being a game dev and me a game prof might make more sense for us to work with those 4, for example) I also said that RIT’d be willing to do more than six but less than a full 50/50 across the full number of teams they have in the three cohorts.

5.  I expect that now through end of June will be the most work intensive with us building these rubrics, spreadsheets and dashboards and then building individual 6 month plans for them with milestones, etc.  after that I figure something like alternating informal calls and formal stand-ups every week is the main effort, plus whatever work we need to do in-between to support them.

6. We should consider grouping them by time zone and doing those stand-ups in groups so they can learn from each other, regardless of what cohort they were in.  E should build a master list, like what Kent has, for all the teams. 

7.  I figure if you do what Flory and Kent have been doing, diving into repos and online presence and calling each team to determine what state they’re all in, we can build the individual 6 months plans for all of them as a team, chart their plans all out together, and then divy em up.

Thoughts?

**Comment by Nolski** [comment]
> 3.  You should be asking them if they expect Gates to also fit under that cap and $ amount or if they’re raising your cap and hours to 1.5  or 2 times the advertised position.

They definitely seem open to increasing the amount of time I work under them, however I want to be sure that time is needed as I have other contracts I'm working on as well.

> 4. You should also know that I told them RIT’d be coordinating efforts with you, and willing to shuffle who works with who (Kent being a game dev and me a game prof might make more sense for us to work with those 4, for example) I also said that RIT’d be willing to do more than six but less than a full 50/50 across the full number of teams they have in the three cohorts.

Yeah I reinforced this to them as well. I have been mostly speaking with Ibrahim and Meghan so maybe they were out of the loop somehow.

> 7.  I figure if you do what Flory and Kent have been doing, diving into repos and online presence and calling each team to determine what state they’re all in, we can build the individual 6 months plans for all of them as a team, chart their plans all out together, and then divy em up.

This is a good plan. I suspect we will have a different level of requirements for certain teams though. Some might have a lot of questions about how their business model, software architecture, etc ties into their open source community plan. My main concern is this can end up being a large (but imo, useful) time sink and just want to try and best allocate hours for it.
